from typing import List, Optional
from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session
from app.database import get_db
from app.models import Forecast
from app.schemas import ForecastItem

router = APIRouter(prefix="/api/forecasts", tags=["Forecasts"])


@router.get("", response_model=List[ForecastItem])
def get_forecasts(
    station: Optional[str] = Query(None, description="Filter by station name"),
    horizon: Optional[int] = Query(None, description="Filter by horizon in hours (6, 12, 24, 48)"),
    db: Session = Depends(get_db),
):
    """
    Returns pre-computed, stored forecasts generated by the background ML pipeline.
    Deterministic: Forecasts are read directly from persistent storage, not calculated on-the-fly.
    """
    query = db.query(Forecast)

    if station:
        query = query.filter(Forecast.station_name.ilike(f"%{station}%"))
    if horizon:
        query = query.filter(Forecast.forecast_horizon_hours == horizon)

    # Order by target timestamp ascending
    forecasts = (
        query.order_by(Forecast.station_name, Forecast.target_timestamp.asc())
        .limit(100)
        .all()
    )

    return [
        ForecastItem(
            station_name=f.station_name,
            forecast_horizon_hours=f.forecast_horizon_hours,
            generation_timestamp=f.generation_timestamp,
            target_timestamp=f.target_timestamp,
            predicted_aqi=f.predicted_aqi,
            predicted_pollutants=f.predicted_pollutants or {},
            confidence_lower=f.confidence_lower,
            confidence_upper=f.confidence_upper,
            model_version=f.model_version,
        )
        for f in forecasts
    ]
