"""Initial schema for observations forecasts anomalies worker_logs

Revision ID: 6874e3074b05
Revises: 
Create Date: 2026-10-09 23:26:18.186221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6874e3074b05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_name', sa.String(length=64), nullable=False),
    sa.Column('detection_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observation_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('anomaly_type', sa.String(length=64), nullable=False),
    sa.Column('affected_parameter', sa.String(length=64), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=True),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('event_status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_name', 'observation_timestamp', 'model_version', name='uq_station_obs_model_anomaly')
    )
    op.create_index('idx_anomaly_station_time', 'anomaly_events', ['station_name', 'observation_timestamp'], unique=False)
    op.create_index(op.f('ix_anomaly_events_detection_timestamp'), 'anomaly_events', ['detection_timestamp'], unique=False)
    op.create_index(op.f('ix_anomaly_events_id'), 'anomaly_events', ['id'], unique=False)
    op.create_index(op.f('ix_anomaly_events_observation_timestamp'), 'anomaly_events', ['observation_timestamp'], unique=False)
    op.create_index(op.f('ix_anomaly_events_station_name'), 'anomaly_events', ['station_name'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_name', sa.String(length=64), nullable=False),
    sa.Column('generation_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast_horizon_hours', sa.Integer(), nullable=False),
    sa.Column('predicted_aqi', sa.Integer(), nullable=False),
    sa.Column('predicted_pm25', sa.Float(), nullable=True),
    sa.Column('predicted_pm10', sa.Float(), nullable=True),
    sa.Column('predicted_pollutants', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('cutoff_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence_lower', sa.Float(), nullable=True),
    sa.Column('confidence_upper', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_name', 'target_timestamp', 'model_version', name='uq_station_target_model')
    )
    op.create_index('idx_forecast_station_target', 'forecasts', ['station_name', 'target_timestamp'], unique=False)
    op.create_index(op.f('ix_forecasts_generation_timestamp'), 'forecasts', ['generation_timestamp'], unique=False)
    op.create_index(op.f('ix_forecasts_id'), 'forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_forecasts_station_name'), 'forecasts', ['station_name'], unique=False)
    op.create_index(op.f('ix_forecasts_target_timestamp'), 'forecasts', ['target_timestamp'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_name', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('observation_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pm25', sa.Float(), nullable=True),
    sa.Column('pm10', sa.Float(), nullable=True),
    sa.Column('no2', sa.Float(), nullable=True),
    sa.Column('so2', sa.Float(), nullable=True),
    sa.Column('co', sa.Float(), nullable=True),
    sa.Column('o3', sa.Float(), nullable=True),
    sa.Column('aqi', sa.Integer(), nullable=True),
    sa.Column('aqi_status', sa.String(length=32), nullable=False),
    sa.Column('data_source', sa.String(length=64), nullable=False),
    sa.Column('quality_status', sa.String(length=32), nullable=False),
    sa.Column('freshness_status', sa.String(length=32), nullable=False),
    sa.Column('prediction', sa.Integer(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('anomaly_status', sa.String(length=32), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_name', 'observation_timestamp', name='uq_station_observation_time')
    )
    op.create_index('idx_station_time', 'observations', ['station_name', 'observation_timestamp'], unique=False)
    op.create_index(op.f('ix_observations_id'), 'observations', ['id'], unique=False)
    op.create_index(op.f('ix_observations_ingestion_timestamp'), 'observations', ['ingestion_timestamp'], unique=False)
    op.create_index(op.f('ix_observations_observation_timestamp'), 'observations', ['observation_timestamp'], unique=False)
    op.create_index(op.f('ix_observations_station_name'), 'observations', ['station_name'], unique=False)
    op.create_table('worker_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('records_ingested', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_logs_id'), 'worker_logs', ['id'], unique=False)
    op.create_index(op.f('ix_worker_logs_job_name'), 'worker_logs', ['job_name'], unique=False)
    op.create_index(op.f('ix_worker_logs_started_at'), 'worker_logs', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_logs_started_at'), table_name='worker_logs')
    op.drop_index(op.f('ix_worker_logs_job_name'), table_name='worker_logs')
    op.drop_index(op.f('ix_worker_logs_id'), table_name='worker_logs')
    op.drop_table('worker_logs')
    op.drop_index(op.f('ix_observations_station_name'), table_name='observations')
    op.drop_index(op.f('ix_observations_observation_timestamp'), table_name='observations')
    op.drop_index(op.f('ix_observations_ingestion_timestamp'), table_name='observations')
    op.drop_index(op.f('ix_observations_id'), table_name='observations')
    op.drop_index('idx_station_time', table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_forecasts_target_timestamp'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_station_name'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_generation_timestamp'), table_name='forecasts')
    op.drop_index('idx_forecast_station_target', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_anomaly_events_station_name'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_observation_timestamp'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_id'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_detection_timestamp'), table_name='anomaly_events')
    op.drop_index('idx_anomaly_station_time', table_name='anomaly_events')
    op.drop_table('anomaly_events')
    # ### end Alembic commands ###
